---

- hosts: synapse
  become: yes
  tasks:
    - name: Install packages needed to compile coturn server
      action: apt pkg={{item}} state=installed
      with_items:
       - gcc
       - make
       - autoconf
       - libevent-dev
       - libsqlite3-dev

    - name: Clone coturn from github
      git: repo=https://github.com/coturn/coturn.git dest=/usr/src/coturn

    - name: Compile and install coturn
      shell: ./configure && make && make install
      args:
        chdir: /usr/src/coturn

    - name: Install turnserver config
      template:
        src=etc/turnserver.conf
        dest=/etc/turnserver.conf

    - name: Install upstart script
      template:
        src=etc/init/turnserver.conf
        dest=/etc/init/turnserver.conf

    - name: Start turn server
      service: name=turnserver state=started
