---

- name: install basic packages that we want to be on all nodes
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items:
   - wget
   - git

- include: synapse.yml
- include: coturn.yml
